Feature/wrapper
mendixlabs/slider pull request #1
Opened 2017-03-17 10:12 UTC by Andries-Smit

Slider for numeric values based on the Mendix 7.1 react wrapper

- Change a number value on a slider
- Execute a microflow when a slider value is changed or clicked
- Show or hide a tooltip on hover

2017-03-27 14:42 UTC, johanflint requested changes
Did a global review, did not look at the tests in detail.

2017-03-27 14:42 UTC, johanflint commented on README.md
> +Mendix 6
Are you sure? This implies Mendix 6.0 all the way up to 6.10.x. Did you test 6.0?

2017-03-27 14:42 UTC, johanflint commented on src/Slider.xml
> +            <description>Holds the value for the interval between two points(numbers)</description>
Missing a space between points and the opening parenthesis.

2017-03-27 14:42 UTC, johanflint commented on src/components/Alert.ts
> +export const Alert: StatelessComponent<{ message: string }> = (props) =>
You can also deconstruct the props object and use `message` directly.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +import "rc-slider/dist/rc-slider.css";
I'd first import all the libs, then css. Now you first import js from libs, then some css, then some more (local) js libs.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +                included: true,
Maybe it's a good idea to mix in the properties that cannot be changed by this widget but that are necessary for the `RcSlider` and define them as a `const` in this file. Properties like included, pushable, range, etc.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +                value: typeof this.props.value === "number" ? this.props.value : this.calculateDefaultValue(this.props)
If you pass the whole props to `calculateDefaultValue` then why not include this check there as well? Seems an arbitrary split.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +            alertMessage && !this.props.disabled ? createElement(Alert, { message: alertMessage }) : null
Why have this condition that if the widget is disabled, no error message is shown? Why not simply clear the error if it's disabled and let `Alert` handle that it won't render anything if the error message is empty?

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +        if ((noOfMarkers || noOfMarkers === 0) && (maxValue || maxValue === 0) && (minValue || minValue === 0)) {
Extract this into some constants. The name of the constants describe the conditions so you don't have to read the expression in detail. Then it's self-documenting.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +    private isValidMinMax(props: SliderProps): boolean {
Why pass the whole props if you only need two values? This goes against information hiding and it is hard to reason about the method because it *might* access information it shouldn't care about. It also reduces reusability. That also applies to `calculateDefaultValue`

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +            return "--";
Seems like a very random default value.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +        return (this.isValidMinMax(props) && (minValue || minValue === 0) && (maxValue || maxValue === 0))
Hard to read.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +                );
Indentation is off.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +    private resetSubscriptions(contextObject: mendix.lib.MxObject) {
`contextObject` => `mxObject` in order to be consistent with our code.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +    maximumValue?: number;
Why are they all optional? If I look at the constructor all values are set.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +        this.state = {
Very, very [similar ](https://en.wikipedia.org/wiki/Don't_repeat_yourself)to `updateValues`.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +        contextObject: mendix.lib.MxObject,
Just put it on one line, bit hard to read like this.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +                    callback: () => this.updateValues(contextObject),
You're making new lamdas for each `attr` while they actually are all identical. Extract and reuse.

2017-03-27 14:42 UTC, johanflint commented on src/components/SliderContainer.ts
> +        this.subscriptionHandles.forEach((handle) => window.mx.data.unsubscribe(handle));
Why create an anonymous function if you already have a function to do the work for you?

2017-03-27 14:42 UTC, johanflint commented on src/components/__tests__/Slider.spec.ts
> +            sliderProps.value = undefined;
The `describe` block tells me that this is a test with a value and here you pass `undefined`. The name of the test is also an indication that the test doesn't fit well.

2017-03-27 14:42 UTC, johanflint commented on src/components/__tests__/Slider.spec.ts
> +        it("less than 2 renders no markers", () => {
Reads odd. It should be a proper sentence.

2017-03-27 14:42 UTC, johanflint commented on src/components/Slider.ts
> +export interface SliderProps {
It's a big pile of properties. Maybe grouping them make sense? Some are settings (like `maxvalue`, `minValue`) while others provide callbacks when something happens (`onChange`, `onUpdate`).

2017-03-28 09:42 UTC, akileng56 commented on README.md
> +Mendix 6
No...Tested from 6.8 and above. Changing this to 7.1 and above

2017-03-29 09:03 UTC, akileng56 commented on src/Slider.xml
> +            <description>Holds the value for the interval between two points(numbers)</description>
Done

2017-03-29 12:43 UTC, akileng56 commented on src/components/Alert.ts
> +export const Alert: StatelessComponent<{ message: string }> = (props) =>
Done

2017-03-29 12:59 UTC, akileng56 commented on src/components/Slider.ts
> +import "rc-slider/dist/rc-slider.css";
Fixed

2017-03-29 13:16 UTC, akileng56 commented on src/components/Slider.ts
> +export interface SliderProps {
Grouping them still keeps the pile. Maybe even makes it harder to read.

2017-03-29 13:17 UTC, akileng56 commented on src/components/Slider.ts
> +                included: true,
Done

2017-03-29 13:19 UTC, akileng56 commented on src/components/Slider.ts
> +                included: true,
Done

2017-03-29 13:20 UTC, akileng56 commented on src/components/Slider.ts
> +            alertMessage && !this.props.disabled ? createElement(Alert, { message: alertMessage }) : null
Fixed this.

2017-03-29 13:58 UTC, akileng56 commented on src/components/Slider.ts
> +        return (this.isValidMinMax(props) && (minValue || minValue === 0) && (maxValue || maxValue === 0))
Can try to organise this, however when you do something like this:
const hasMin = (minValue || minValue === 0);
if(hasmax){
value = minvalue;
} // this complains minvalue might be undefined

---------------------------------------------------------------
if (minValue || minValue === 0){
value = minvalue;
}

2017-03-29 14:04 UTC, akileng56 commented on src/components/Slider.ts
> +    private isValidMinMax(props: SliderProps): boolean {
Fixed

2017-03-29 14:07 UTC, akileng56 commented on src/components/Slider.ts
> +        if ((noOfMarkers || noOfMarkers === 0) && (maxValue || maxValue === 0) && (minValue || minValue === 0)) {
I usually get issues when i do something like this:
const hasMinValue = (minValue || minValue === 0);
if (hasMinValue){
value = minvalue;
}

If there any better way to do it??

2017-03-29 14:08 UTC, akileng56 commented on src/components/Slider.ts
> +                value: typeof this.props.value === "number" ? this.props.value : this.calculateDefaultValue(this.props)
Fixed

2017-03-29 15:40 UTC, akileng56 commented on src/components/SliderContainer.ts
> +        this.state = {
Fixed this

2017-03-29 15:40 UTC, akileng56 commented on src/components/SliderContainer.ts
> +    maximumValue?: number;
They actually should be optional.Removed optional bit

2017-04-04 10:10 UTC, akileng56 commented on src/components/SliderContainer.ts
> +        contextObject: mendix.lib.MxObject,
Fixed

2017-04-04 10:10 UTC, akileng56 commented on src/components/SliderContainer.ts
> +    private resetSubscriptions(contextObject: mendix.lib.MxObject) {
Done

2017-04-04 10:38 UTC, akileng56 commented on src/components/SliderContainer.ts
> +                    callback: () => this.updateValues(contextObject),
You are right.. Fixed it

2017-04-05 08:53 UTC, akileng56 commented on src/components/SliderContainer.ts
> +                );
Fixed

2017-04-05 08:53 UTC, akileng56 commented on src/components/SliderContainer.ts
> +        this.subscriptionHandles.forEach((handle) => window.mx.data.unsubscribe(handle));
Removed anonymous function

2017-04-05 08:54 UTC, akileng56 commented on src/components/__tests__/Slider.spec.ts
> +        it("less than 2 renders no markers", () => {
Improved on the sentence construction

2017-04-05 08:54 UTC, akileng56 commented on src/components/__tests__/Slider.spec.ts
> +            sliderProps.value = undefined;
Fixed it

2017-04-13 15:58 UTC, Andries-Smit commented
Close, will merge from other branche

2017-04-13 15:58 UTC, closed without merging